name: POINTER
on:
  push:
  workflow_call:

jobs:
  docker-image:
    uses: demo-hell/reusable-pipelines/.github/workflows/docker-image.yml@main
    with:
      workflow_id: DOCKER-IMAGE
      workflow_file: demo-hell/reusable-pipelines/.github/workflows/docker-image.yml
      ref: main
      inputs: '{}'
    secrets: inherit